(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var I0=function(a){a.V("cardstatechange",a.Lg()&&a.Ni()?1:0)},J0=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},SDa=function(a){var b=g.Bg(a);
a=g.Hg(a);return new g.$f(b.x,b.y,a.width,a.height)},TDa=function(a){return Math.pow(a,3)},UDa=function(a){return 3*a*a-2*a*a*a},M0=function(a){a=g.Oa(a);
delete K0[a];g.Mb(K0)&&L0&&L0.stop()},WDa=function(){L0||(L0=new g.L(function(){VDa()},20));
var a=L0;a.isActive()||a.start()},VDa=function(){var a=g.C();
g.Ab(K0,function(b){XDa(b,a)});
g.Mb(K0)||WDa()},N0=function(a,b,c,d){g.un.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.I=0;this.B=null},XDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.B);a.B=b;YDa(a,a.progress);1==a.progress?(a.Ma=0,M0(a),a.onFinish(),a.Ar()):a.Kb()&&a.kw()},YDa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},ZDa=function(a,b){g.Hl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Ma},O0=function(a,b,c,d,e){N0.call(this,b,c,d,e);
this.element=a},P0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
O0.call(this,a,b,c,d,e)},Q0=function(a){g.I.call(this);
this.l=a||window;this.i=[]},R0=function(a){return a.baseUrl||null},S0=function(a,b){return g.He(g.Jc(a,b,void 0),function(c){return!!c})},$Da=function(a,b,c){function d(cb){var nb,Ad,Ub,jc=cb.hovercardButton;
if(!jc)return null;jc=jc.subscribeButtonRenderer;if(!jc)return null;var cf=f(jc.unsubscribedButtonText),df=f(jc.subscribedButtonText);if(jc.subscribed){var ql=f(jc.subscriberCountWithUnsubscribeText);var pi=f(jc.subscriberCountText)}else ql=f(jc.subscriberCountText),pi=f(jc.subscriberCountWithSubscribeText);var Lf=null;return cb.signinEndpoint&&(Lf=J0(cb,"signinEndpoint","webNavigationEndpointData","url"),Lf||(Lf=null===(Ub=null===(Ad=null===(nb=jc.signInEndpoint)||void 0===nb?void 0:nb.commandMetadata)||
void 0===Ad?void 0:Ad.webCommandMetadata)||void 0===Ub?void 0:Ub.url),!Lf)?null:cf&&(df||Lf)?{subscribed:jc.subscribed,subscribeText:cf,subscribeCount:ql,unsubscribeText:df,unsubscribeCount:pi,enabled:jc.enabled,signinUrl:Lf,classic:cb.useClassicSubscribeButton}:null}
function e(cb){if(cb){var nb=[],Ad=cb.videoId;Ad&&nb.push("v="+Ad);(Ad=cb.playlistId)&&nb.push("list="+Ad);(cb=cb.startTimeSeconds)&&nb.push("t="+cb);return"/watch?"+nb.join("&")}}
function f(cb){if(!cb)return null;var nb=cb.simpleText;return nb?nb:cb.runs?g.Jc(cb.runs,function(Ad){return Ad.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,F=null,D=null,G=null,J=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=J0(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):F=f(b.subscribersText)}else"WEBSITE"===
h?((D=J0(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(J=f(b.additionalFeesText)),(n=J0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=J0(b,"title","accessibility","accessibilityData","label");var H=b.endpoint?b.endpoint.clickTrackingParams:null,Aa="";if(b.metadata){var na=f(b.metadata);na&&(Aa=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Aa,callToAction:f(b.callToAction),
XC:b.image,iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:F,isSubscribe:x,targetUrl:m||null,SL:n,Bd:H?{itct:H}:null,BQ:p,bq:a?a:null,VL:b.isPlaceholder,impressionUrls:S0(b.impressionUrls||[],R0),LL:S0(b.hovercardShowUrls||[],R0),clickUrls:S0(l.loggingUrls||[],R0),visualElement:g.du(b.trackingParams),
productPrice:G,additionalFeesText:J}},T0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:S0(a.impressionUrls||[],R0),elements:S0(a.elements||[],function(d,e){return $Da(b,d,e)})};
a.trackingParams&&(c.visualElement=g.du(a.trackingParams));return c},U0=function(a){g.HN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.L=g.TC(a)||g.WC(a);this.events=new g.zN(this);g.K(this,this.events);this.events.N(this.player,g.OF("creatorendscreen"),this.yd);this.events.N(this.player,g.PF("creatorendscreen"),this.kf);this.events.N(this.player,"resize",this.Sa);this.events.N(window,"focus",this.CP);this.load();var b=g.Ce("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Pi(this,function(){g.Ge(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},aEa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},V0=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},bEa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=T0(f,aEa(a))));W0(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.dm;d&&(c.postParams={ad_tracking:d});if(b=g.Uia(b))if(b=g.Ec(b),b=g.Ac(b))a.u=g.Yp(b,c)},W0=function(a,b,c){c=void 0===c?!0:c;
a.player.Oe("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&cEa(a);c=[];d=new g.LF(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.W({D:"div",K:"ytp-ce-shadow"}),g.xN(a.player,a.l.element,4),a.B=new g.eM(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=dEa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.xN(a.player,f.element,4);var h=new g.LF(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);eEa(a,f,e)}else g.it(new g.Yr("buildEndscreenElement null",
e))}a.player.Id(c);a.Sa()}},cEa=function(a){var b=g.hu(),c=g.ju();
c&&b&&a.endscreen.visualElement&&g.xu(c,b,a.endscreen.visualElement)},dEa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ka:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:X0(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:Y0(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",ka:["ytp-ce-video-title"].concat(g.la(c)),U:{dir:g.An(b.title||
"")},ba:b.title},{D:"div",K:"ytp-ce-video-duration",ba:b.videoDuration||void 0}]}]};c=new g.W(c);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ka:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:X0(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:Y0(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",ka:["ytp-ce-playlist-title"].concat(g.la(c)),U:{dir:g.An(b.title||"")},ba:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ba:b.playlistLength||void 0}]}]}]};c=new g.W(c);break;case "CHANNEL":c={D:"div",ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",ka:["ytp-ce-channel-title","ytp-ce-link"],U:{href:Y0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.An(b.title||"")},ba:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ba:b.subscribersText}:"",b.metadata?{D:"div",ka:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ba:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:X0(b)}]};c=new g.W(c);var d=g.oe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Bd.itct}else e="endscreen",f=null;e=new g.IO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={D:"div",ka:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.An(b.title||"")},ba:b.title},{D:"div",K:"ytp-ce-website-metadata",ba:b.metadata},{D:"a",ka:["ytp-ce-website-goto","ytp-ce-link"],U:{href:Y0(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:X0(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:fEa(b.iconUrl)}]};c=new g.W(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ba:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ba:b.additionalFeesText})),c={D:"div",ka:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.An(b.title||"")},ba:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ba:b.metadata},{D:"a",ka:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:Y0(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:X0(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ba:b.callToAction||void 0}]}]},c=new g.W(c)}b.VL&&g.M(c.element,"ytp-ce-placeholder");return c},X0=function(a){if(a.XC)var b=a.XC.thumbnails;
return fEa(b?b[b.length-1].url:null)},fEa=function(a){return a?{style:"background-image: url("+a+")"}:{}},eEa=function(a,b,c){function d(m){m&&(b.ya("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.M(b.element,"ytp-ce-force-expand"),Z0(a,c.id,!0)):(g.rn(b.element,"ytp-ce-force-expand"),g.rn(b.element,"ytp-ce-element-hover"),Z0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.ya("mouseenter",function(){$0(a,b,c)});
b.ya("mouseleave",function(){a1(a,b,c)});
a.player.T().i||b.ya("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.ya("click",function(m){gEa(a,c,m)});
b.ya("keypress",function(m){gEa(a,c,m)});
b.ya("focus",function(){$0(a,b,c)});
b.ya("blur",function(){a1(a,b,c)});
b.ya("touchstart",function(){$0(a,b,c)});
var l=g.qe("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.rn(b.element,"ytp-ce-element-hover");g.rn(b.element,"ytp-ce-force-expand")});
b.ya("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.qe("ytp-sb-subscribe",b.element));d(g.qe("ytp-sb-unsubscribe",b.element));b.ya("focus",f);b.ya("blur",h)},gEa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.pn(d,"ytp-ce-element");){g.pn(d,"subscribe-label")&&b1(a,b);
if(g.pn(d,"ytp-ce-channel-subscribe"))return;d=g.Ie(d)}if(!d||g.pn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])a1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.BQ)b1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Ec(Y0(a,b.targetUrl)),c=g.Ac(c),g.cK(c,void 0,b.Bd);else{var e=a.player.getVideoData().C,f=function(){var h=Y0(a,b.targetUrl),l=b.Bd,m=g.Gp(h);e&&m&&(m.v||m.list)?a.player.Fi(m.v,l,m.list,!1):g.bK(h,l)};
b1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Y0=function(a,b){var c=a.player.T();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.zD(c)+b}else return"";return b},$0=function(a,b,c){g.pn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),c1(a,c.LL),Z0(a,c.id,!0))},a1=function(a,b,c){g.rn(b.element,"ytp-ce-element-hover");
g.rn(b.element,"ytp-ce-force-expand");Z0(a,c.id,!1)},Z0=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},c1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||V0(a))c&&c();else{b=hEa(a,b);var e=0,f=!1,h=new g.L(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.uq(b[a],d)}},b1=function(a,b,c){c1(a,b.clickUrls,c);
(a=g.ju())&&b.SL&&g.Au(a,b.visualElement)},hEa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(a.zz(b[e],c));return d},iEa=function(a){return Array.isArray(a)&&a.length?a[0]:a},d1=function(a){return"string"===typeof a?a:""},e1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jEa=function(a){this.externalId=a},kEa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},f1=function(a){return a.value?a.value:null},g1=function(a){if(!a)return null;
var b=g.Ec(d1(a.value));b=g.Ac(b);if(!b)return null;var c=e1(a.target,lEa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new kEa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},mEa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},pEa=function(a){if(!a)return null;
var b=e1(a.type,nEa),c=e1(a.trigger,oEa),d=iEa(a.url);d=g1(d?d:null);a=iEa(a.subscribeData);var e=a?a:null;e?(a=d1(e.external_user_id),e=d1(e.subscription_token),a=a&&e?new jEa(a):null):a=null;return b?new mEa(b,c,d,a):null},qEa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},sEa=function(a){return(a=rEa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},rEa=function(a,b){return g.$a(a.action,b,void 0)},tEa=function(a,b){this.context=a;
this.i=b},i1=function(a){return a.customMessage?h1("div","iv-card-message",a.customMessage):""},j1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",K:"iv-card-image",U:{style:c},S:d}},k1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(h1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},h1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.An(c);return{D:a,U:b,ba:c}},uEa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Ws&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Ws+");");c.dir=g.An(a.customMessage);var d=[{D:"span",ba:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",ka:b,U:c,S:d}},l1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Bd,c.kg.click,5)}},vEa=function(a,b){this.merchant=a;
this.price=b},wEa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},xEa=function(a,b){return b?b:wEa(a)?"current":"new"},m1=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.Ka=!1;this.za=new Map;this.Da=new Map;this.context.G.addEventListener(g.OF("annotations_module"),function(d){(d=c.za.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.PF("annotations_module"),function(d){(d=c.Da.get(d))&&d.apply(c)})},n1=function(a,b,c,d,e,f,h){a.context.i.ya(b,"click",function(l){a.lw(c,d,e,f||[],h||0,l)});
a.context.i.ya(b,"touchstart",function(){a.Ka=!1});
a.context.i.ya(b,"touchmove",function(){a.Ka=!0})},yEa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},o1=function(a,b,c){return{UD:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
WG:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
gv:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},r1=function(a,b,c){m1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.la=this.Xa=this.u=this.de=!1;this.ca=null;this.cards=[];this.Pa=this.L=this.ga=this.C=this.ma=this.i=null;this.X=[];this.J=this.Sd=this.ia=null;this.I=0;this.ea=new g.L(g.Ia,c.B.qd?4E3:3E3);g.K(this,this.ea);this.Ha=new g.L(g.Ia);g.K(this,this.Ha);this.Y=new tEa(c,function(e,f,h,l,m,n){n1(d,e,f,h,l,m,n)});
this.W=new g.W({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",ka:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.K(this,this.W);this.B=this.W.element;this.Ia=new g.eM(this.W,330);g.K(this,this.Ia);this.Wa=g.qe("iv-drawer-header-text",this.B);this.l=g.qe("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Xa&&p1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Xa=d.u)&&q1(d)})},zEa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){p1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){q1(a)});
var d=c.headerText;g.Ke(a.Wa,d);a.L&&a.L.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.ia=g.du(c.trackingParams);a.J=g.du(c.closeTrackingParams);a.Sd=g.du(c.iconTrackingParams)},AEa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:s1(a,c,b,d),sponsored:!1,kg:o1(d,e,d.command),Sj:d.trackingParams?g.du(d.trackingParams):null,Lh:e.trackingParams?g.du(e.trackingParams):
null,Sd:f&&f.trackingParams?g.du(f.trackingParams):null,imageUrl:t1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.U(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Ws:null,title:d.title?g.U(d.title):"",customMessage:d.callToAction?g.U(d.callToAction):"",url:d.command.urlEndpoint.url?g1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};u1(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:s1(a,c,b,d),sponsored:!1,kg:o1(d,e,d.endpoint),Sj:d.trackingParams?g.du(d.trackingParams):null,Lh:e.trackingParams?g.du(e.trackingParams):null,Sd:f&&f.trackingParams?g.du(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.U(d.customText):null,dG:t1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.U(d.channelName):"",metaInfo:[d.subscriberCountText?g.U(d.subscriberCountText):""],url:g1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};u1(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:s1(a,c,b,d),sponsored:!1,kg:o1(d,e,d.action),Sj:d.trackingParams?g.du(d.trackingParams):null,Lh:e.trackingParams?g.du(e.trackingParams):null,Sd:f&&f.trackingParams?g.du(f.trackingParams):
null,ls:t1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.U(d.customMessage):null,playlistVideoCount:g.U(d.playlistVideoCount),title:d.playlistTitle?g.U(d.playlistTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.videoCountText?g.U(d.videoCountText):""],url:g1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:yEa(d.action)})};u1(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:s1(a,c,b,d),sponsored:!1,kg:o1(d,e,d.action),Sj:d.trackingParams?g.du(d.trackingParams):null,Lh:e.trackingParams?g.du(e.trackingParams):null,Sd:f&&f.trackingParams?g.du(f.trackingParams):null,ls:t1(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.U(d.lengthString):null,customMessage:d.customMessage?g.U(d.customMessage):null,title:d.videoTitle?g.U(d.videoTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.viewCountText?g.U(d.viewCountText):""],isLiveNow:!!d.badge,url:g1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:yEa(d.action)})};u1(a,c)}a.I++},t1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},s1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},CEa=function(a,b){var c=BEa(a,b);
c&&(c===a.i&&(a.i=null),a.G.removeCueRange(c.card.id),g.Ge(c.Zw),g.ib(a.cards,c),a.Ys(),v1(a))},p1=function(a,b,c){if(!a.u){a.Ia.show();
a.ma=new g.L(function(){g.M(a.context.G.getRootNode(),g.gT.IV_DRAWER_OPEN)},0);
a.ma.start();a.ca=g.ap(a.l,"mousewheel",function(h){a.ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.ju();d&&a.ia&&a.J&&g.yu(d,[a.ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.AE||(f.AE=!0,DEa(a.context.logger,f.card.kg.UD,b)),d&&g.yu(d,[f.card.Sj]);I0(a.G);c&&(a.C=new g.L(function(){a.ga=a.L;a.Pa.focus()},330),a.C.start())}},q1=function(a){a.u&&(a.Ia.hide(),g.bp(a.ca),a.ca=null,g.rn(a.context.G.getRootNode(),g.gT.IV_DRAWER_OPEN),a.u=!1,I0(a.G),a.C&&a.C.stop(),a.C=new g.L(function(){a.ga&&(a.ga.focus(),a.ga=null)},330),a.C.start())},FEa=
function(a){g.qn(a.element,[g.gT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.xN(a.G,a.B,5);EEa(a);a.L=g.qe("ytp-cards-button",a.G.getRootNode());a.Pa=g.qe("iv-drawer-close-button",a.B);a.de=!0},EEa=function(a){var b=g.qe("iv-drawer-close-button",a.B);
a.context.i.ya(b,"click",a.CK,a);a.context.i.ya(a.l,"touchend",function(){a.ea.start()});
a.context.i.ya(a.l,"scroll",a.NK,a);a.context.l.subscribe("onHideControls",function(){a.la=!0});
a.context.l.subscribe("onShowControls",function(){a.la=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.la=g.pn(a.G.getRootNode(),"ytp-autohide")});
a.X.push(g.Go("iv-button-shown",a.ZL,a));a.X.push(g.Go("iv-button-hidden",a.YL,a));a.X.push(g.Go("iv-teaser-shown",a.eJ,a));a.X.push(g.Go("iv-teaser-hidden",a.bM,a));a.X.push(g.Go("iv-teaser-clicked",a.dJ,a))},u1=function(a,b){a.de||FEa(a);
CEa(a,b.id);var c=GEa(a,b);if(c){var d={card:b,Zw:c.element,AE:!1},e=HEa(a,d);g.qb(a.cards,e,0,d);c.fa(a.l,e);a.Ys();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,v1(a),IEa(a,d),p1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&JEa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){JEa(a,d)}),v1(a))}},GEa=function(a,b){switch(b.type){case "simple":var c=a.Y;
var d=b.displayDomain?{D:"div",K:"iv-card-image-text",ba:b.displayDomain}:void 0;var e=uEa(b);d={D:"div",ka:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?f1(b.url)||"":""},S:[j1(b.imageUrl,d),{D:"div",K:"iv-card-content",S:[h1("h2",void 0,b.title),e]}]}]};d=new g.W(d);l1(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.Y,d={D:"div",ka:["iv-card","iv-card-channel"],S:[{D:"a",ka:["iv-click-target"],U:{href:f1(b.url)||"","data-ytid":b.channelId},S:[j1(b.dG),
{D:"div",K:"iv-card-content",S:[i1(b),{D:"h2",K:"iv-card-primary-link",ba:b.title},k1(b)]}]}]},d=new g.W(d),l1(c,g.pe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.Y,d={D:"div",ka:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:f1(b.url)||""},S:[j1(b.ls,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ba:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[i1(b),h1("h2","iv-card-primary-link",b.title),k1(b)]}]}]},d=new g.W(d),
l1(c,g.pe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.Y;var f=!g.eb(b.offers);d=["iv-card"];e="";var h=uEa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",K:"iv-card-offer-price",ba:h.price}),h.merchant&&f.push({D:"div",K:"iv-card-offer-merchant",ba:h.merchant}),h={D:"div",S:f});f=b.url?f1(b.url)||"":"";d={D:"div",ka:d,U:{tabindex:"0"},S:[{D:"a",ka:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ba:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:f},S:[h1("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.Ce("span");g.Ke(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Fc(e,"adInfo");l1(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.Y,e=b.videoDuration?{D:"span",K:"iv-card-video-duration",ba:b.videoDuration}:void 0,h=b.isLiveNow?{D:"span",ka:["yt-badge","yt-badge-live"],ba:"LIVE NOW"}:null,e={D:"div",ka:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(d=b.url)||void 0===d?void 0:f1(d))||""},S:[j1(b.ls,e),{D:"div",K:"iv-card-content",S:[i1(b),h1("h2","iv-card-primary-link",b.title),k1(b),h]}]}]},d=new g.W(e),
l1(c,g.pe("iv-click-target",d.element),b,b.url),d;default:return null}},HEa=function(a,b){if(0===a.cards.length)return 0;
var c=g.ab(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},KEa=function(a){return a.i?"productListing"===a.i.card.type:g.nh(a.cards,function(b){return"productListing"===b.card.type})},v1=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",KEa(a))},JEa=function(a,b){if(!g.pn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.ju(),d=a.i?a.i.card.Sd:a.Sd;
c&&d&&g.zu(c,[d]);a.i=b;v1(a)}if(c="none"!=a.element.style.display)g.S(a.context.G.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.G.getPresentingPlayerType()?(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.G.getAdState();c&&b.card.teaserDurationMs&&a.G.tp(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ha.isActive()||((!a.u||!a.ea.isActive()&&a.la)&&IEa(a,b),a.Ha.start(910+b.card.teaserDurationMs))}},
IEa=function(a,b){if(a.W.ab){var c=new N0([0,
a.l.scrollTop],[0,b.Zw.offsetTop],600,UDa);a.context.u.ya(c,"animate",function(d){a.l.scrollTop=d.y});
a.context.u.ya(c,"finish",function(d){a.l.scrollTop=d.y});
c.play()}else g.rL(a.W,!0),a.l.scrollTop=b.Zw.offsetTop,g.rL(a.W,!1)},w1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},BEa=function(a,b){return g.$a(a.cards,function(c){return c.card.id===b})},x1=function(a,b,c){m1.call(this,a,b);
this.annotation=c;this.isActive=!1},LEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},y1=function(a,b,c){x1.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},MEa=function(a,b){var c=void 0===c?0:c;
var d=SDa(b).width;g.zg(b,d);c=new P0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,TDa);g.K(a,c);a.context.u.ya(c,"begin",function(){g.Ig(b,!0)});
c.play()},PEa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
ka:["iv-branding-context-name"],ba:b.channel_name}),d=a.createElement({D:"div",ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.IO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.i.fa(d));var f=a.createElement({D:"div",ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",ka:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ig(h,!1);var l=a.createElement({D:"div",ka:["branding-context-container-outer"]});l.appendChild(h);g.pg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.L(function(){NEa(a,h,l)},500);
g.K(a,a.u);a.context.i.ya(a.element,"mouseover",function(){OEa(a,h,l,f,b.image_height)});
a.context.i.ya(a.element,"mouseout",function(){a.u.start()})}},OEa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Hg(b);a.i||(b.style.width=g.yg(f.width,!0),c.style.width=g.yg(f.width,!0));g.pg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.pg(d,"right","1px");a.B=!0;g.Ig(b,!0);a.C=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.C.start()}},NEa=function(a,b,c){g.rn(a.element,"iv-branding-active");
a.I=new g.L(function(){g.Ig(b,!1);a.i||(c.style.width=g.yg(0,!0))},250);
a.I.start();a.B=!1},QEa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.l=h},z1=function(a,b,c){x1.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.W=!1;this.I=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",ka:["iv-promo-contents"]});this.C=new g.L(function(){d.i.setAttribute("aria-hidden","true");g.Ig(d.u,!1);g.Ig(d.l,!0)},700,this);
g.K(this,this.C)},REa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=sEa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",ka:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ba:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ba:b.playlist_length.toString()}),h.appendChild(f));e&&n1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.ed(f,f1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ba:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ba:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",ka:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",ka:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ba:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&n1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&n1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ba:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ba:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",ka:["yt-badge","iv-promo-badge-live"],ba:"LIVE NOW"})),g.M(a.i,"iv-click-target"),e&&n1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",ka:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.ya(a.l,"click",function(r){A1(a,5E3,r)});
c.appendChild(a.l);g.Ig(a.l,!1);a.context.i.ya(a.element,"mouseover",a.uL,a);a.context.i.ya(a.element,"mouseout",a.tL,a);a.context.i.ya(a.element,"touchend",function(r){A1(a,5E3,r)});
a.u=a.createElement({D:"button",ka:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.ya(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.oL:a.nL,a);c.appendChild(a.u);g.qn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},A1=function(a,b,c){c.stopPropagation();
SEa(a);TEa(a,b);a.i.focus()},UEa=function(a){a.isCollapsed||a.L||a.B||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},SEa=function(a){a.C.stop();
a.isCollapsed&&(g.sn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Ig(a.l,!1),g.Ig(a.u,!0))},TEa=function(a,b){a.B||(a.B=g.Lm(function(){B1(this);
UEa(this)},b,a))},B1=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},VEa=function(a){this.G=a},DEa=function(a,b,c){b&&(c?C1(a,b.map(function(d){return g.en(d,c)})):C1(a,b))},C1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.uq(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},D1=function(a){g.HN.call(this,a);
var b=this;this.W=!1;this.loadNumber=0;this.J={};this.logger=new VEa(this.player);this.C=new g.zN(this);this.I=this.u=null;this.events=new g.zN(this);this.L=this.i=null;this.X=[];g.K(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.V("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.V("onShowControls")});
this.C.N(this.player,"resize",function(d){b.V("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.fJ,this);this.subscribe("resize",this.Du,this);this.player.T().L.subscribe("vast_info_card_add",this.QF,this);g.K(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.W({D:"div",ka:["ytp-player-content","ytp-iv-player-content"]});g.K(this,this.l);g.xN(this.player,this.l.element,4);this.l.hide();this.B=new g.W({D:"div",ka:["ytp-iv-video-content"]});g.K(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.En()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Pi(this,function(){g.Ge(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},WEa=function(a){a=a.createElement({D:"div",
ka:["annotation","annotation-type-custom"]});g.Ig(a,!1);return a},XEa=function(a,b){var c=!b.isCued()&&!g.V(b,1024);
g.rL(a.l,c);g.rL(a.B,c)},YEa=function(a,b,c){a.W=!0;
a.I=g.Yp(b,c)},ZEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(ZEa(a,e))}return c},bFa=function(a){var b=a.player.getVideoData();
if(b.ca){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Sp(h)&&h.responseXML?h.responseXML:null)&&E1(a,h)}};
g.rp()&&(d.onFinish=$Ea(a,d.onFinish));d.postParams={ic_only:"1"};aFa(d,c);a.W=!0;g.Yp(b.ca,d)}}},aFa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.mq&&(a.postParams.ic_coll=b.mq);b.ht&&(a.postParams.ic_xml=b.ht);b.ts&&(a.postParams.ic_track=b.ts)},cFa=function(a){var b=new g.W({D:"div"});
g.Ig(b.element,!1);var c=new r1(a.player,b.element,F1(a));g.K(c,b);b.fa(a.l.element);c.Tr();return c},F1=function(a){if(!a.L){var b=new Q0(a);
g.K(a,b);var c=new g.u_(a);g.K(a,c);a.L=new QEa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.qd)}return a.L},E1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ju();if(e){var f=g.hu();f&&g.pu(g.Po("use_default_events_client")?void 0:g.at,e,f,[g.du(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=ZEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=e1(h.type,dFa),r=e1(h.style,eFa),t=d1(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=pEa;if(null==x)var y=null;else if(g.La(x)){m=[];for(var F=g.q(x),D=F.next();!D.done;D=
F.next()){var G=h(D.value);G&&m.push(G)}y=m}else{var J=h(x);y=J?[J]:[]}f=n&&p?new qEa(n,p,r,y,w):null}else f=null}catch(Ad){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var H=WEa(h),Aa=null;switch(m.type){case "branding":if(h.player.T().kb)break;h.l.element.appendChild(H);Aa=new y1(H,F1(h),m);break;case "promotion":g.xN(h.player,H,4),Aa=new z1(H,F1(h),m)}Aa&&Aa.Tr();if(h=Aa)g.K(a,h),a.J[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.i||(a.i=cFa(a),g.K(a,a.i));if("card"===f.type){c=
a.i;var na=f&&f.data&&f.data.card_type;h=f.data;if(na)switch(m=h.tracking||{},m={UD:m.impression,click:m.click,close:m.close,WG:m.teaser_impression,gv:m.teaser_click},H=h.tracking_params||{},Aa=null,na){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,kg:m,Sj:H.card?g.du(H.card):null,Lh:H.teaser?g.du(H.teaser):null,Sd:H.icon?
g.du(H.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,dG:h.image_url,title:h.title,metaInfo:h.meta_info,url:g1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};u1(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,kg:m,Sj:H.card?g.du(H.card):null,
Lh:H.teaser?g.du(H.teaser):null,Sd:H.icon?g.du(H.icon):null,ls:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:g1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};u1(c,f);break;case "productListing":h.signin_url&&(Aa=g1({target:"current",value:h.signin_url}));na=[];for(var cb=h.offers||[],nb=0;nb<cb.length;nb++)na.push(new vEa(g.ld(cb[nb].merchant),g.ld(cb[nb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,kg:m,Sj:H.card?g.du(H.card):null,Lh:H.teaser?g.du(H.teaser):null,Sd:H.icon?g.du(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Ws:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:g1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),V3:Aa,U3:h.signin_title?h.signin_title:void 0,T3:h.signin_message?h.signin_message:void 0,offers:na};u1(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,kg:m,Sj:H.card?g.du(H.card):null,Lh:H.teaser?g.du(H.teaser):null,Sd:H.icon?
g.du(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Ws:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:g1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};u1(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,kg:m,Sj:H.card?g.du(H.card):null,Lh:H.teaser?g.du(H.teaser):null,Sd:H.icon?g.du(H.icon):null,ls:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:g1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},u1(c,f)}}else zEa(a.i,f);c=!0}}c&&(I0(a.player),a.Du())},fFa=function(a,b){var c=!1;
a.i||(a.i=cFa(a),g.K(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(AEa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.U(b.headerText):"",g.Ke(c.Wa,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ia=b.trackingParams?g.du(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.du(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Sd=b.icon.infoCardIconRenderer.trackingParams?
g.du(b.icon.infoCardIconRenderer.trackingParams):null,I0(a.player),a.Du())},gFa=function(a,b,c,d,e){if(!a.player.T().kb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new mEa("openUrl","click",new kEa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.U(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.U(b.subscriberCountText))):(b.subscriberCountText&&(e=g.U(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.U(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.U(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.U(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new qEa(c,"branding","branding",f,d);l=WEa(a);a.l.element.appendChild(l);f=new y1(l,F1(a),f);f.Tr();g.K(f,f);a.J[c]=f}},$Ea=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.na()||(d.unshift(b),b=g.Pa.apply(window,d),a.X.push(g.pp(b)))}},hFa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.qN.prototype.tp=g.ca(15,function(a,b){var c=g.SN(this.Ua());c&&c.tp(a,b)});
var K0={},L0=null;g.Ra(N0,g.un);g.k=N0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ma)this.progress=0,this.coords=this.i;else if(this.Kb())return!1;M0(this);this.startTime=a=g.C();-1==this.Ma&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Cu();this.rh("play");-1==this.Ma&&this.rh("resume");this.Ma=1;var b=g.Oa(this);b in K0||(K0[b]=this);WDa();XDa(this,a);return!0};
g.k.stop=function(a){M0(this);this.Ma=0;a&&(this.progress=1);YDa(this,this.progress);this.rh("stop");this.Ar()};
g.k.pause=function(){this.Kb()&&(M0(this),this.Ma=-1,this.rh("pause"))};
g.k.da=function(){0==this.Ma||this.stop(!1);this.rh("destroy");N0.Dd.da.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.kw=function(){this.rh("animate")};
g.k.rh=function(a){this.dispatchEvent(new ZDa(a,this))};
g.Ra(ZDa,g.Hl);g.Ra(O0,N0);O0.prototype.u=g.Ia;O0.prototype.kw=function(){this.u();O0.Dd.kw.call(this)};
O0.prototype.Ar=function(){this.u();O0.Dd.Ar.call(this)};
O0.prototype.Cu=function(){this.u();O0.Dd.Cu.call(this)};
g.Ra(P0,O0);P0.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(Q0,g.I);Q0.prototype.ya=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.ap(a,b,c);this.i.push(a);return a};
Q0.prototype.Ny=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.jp(a,b,c);this.i.push(a);return a};
Q0.prototype.Gb=function(a){g.bp(a);g.ib(this.i,a)};
Q0.prototype.da=function(){g.bp(this.i);this.i.length=0;g.I.prototype.da.call(this)};g.u(U0,g.HN);g.k=U0.prototype;g.k.load=function(){g.HN.prototype.load.call(this);if(!V0(this)){var a=g.Via(this.player.getVideoData());a?(a=T0(a,aEa(this)),W0(this,a,!1)):bEa(this)}};
g.k.unload=function(){W0(this,null);this.u&&(this.u.abort(),this.u=null);g.HN.prototype.unload.call(this)};
g.k.Ge=function(a,b){if(!V0(this))return null;if("loadCustomEndscreenRenderer"===a){var c=T0(b,"new");W0(this,c);return!0}return null};
g.k.getOptions=function(){return V0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Sa=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<iFa.length;f++){var h=Math.abs(b.width-iFa[f]);if(-1===e||d>=h)e=f,d=h}d=jFa[e];this.l&&g.pg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Gg(e.element,Math.round(h.width*a.width),f);g.zg(e.element,m,n);g.sn(e.element,kFa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.sn(e.element,jFa);g.M(e.element,d);(e=g.oe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.pg(e,"height",f+"px")}}}}};
g.k.yd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())c1(this,this.endscreen.impressionUrls),(a=g.ju())&&this.endscreen.visualElement&&g.qu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");c1(this,c.impressionUrls);(b=g.ju())&&g.qu(b,c.visualElement,void 0);this.player.T().u&&this.player.xa("endscreenelementshown",
a)}};
g.k.kf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.rn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.rn(b,"ytp-ce-shown");this.player.T().u&&this.player.xa("endscreenelementhidden",a)}};
g.k.CP=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.sn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.zz=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})};
var iFa=[346,426,470,506,570,640,853,1280,1920],jFa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),kFa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var lEa={uU:"current",SZ:"new"};var nEa={CLOSE:"close",e_:"openUrl",gK:"subscribe"},oEa={oS:"click",CLOSE:"close",OV:"hidden",u0:"rollOut",v0:"rollOver",Z0:"shown"};var eFa={LR:"anchored",GH:"branding",CHANNEL:"channel",sU:"cta",RV:"highlightText",QW:"label",PLAYLIST:"playlist",R_:"popup",l1:"speech",gK:"subscribe",E1:"title",VIDEO:"video",N2:"website"},dFa={GH:"branding",dS:"card",IU:"drawer",QV:"highlight",oY:"marker",Z_:"promotion",TEXT:"text",T2:"widget"};g.u(m1,g.I);g.k=m1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.LF(a,b,{id:c});a.namespace="annotations_module";d&&this.za.set(a,d);e&&this.Da.set(a,e);this.context.G.Id([a])};
g.k.Tr=function(){this.context.l.subscribe("resize",this.Ys,this)};
g.k.lw=function(a,b,c,d,e,f){if(this.Ka)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ge(this.element)};
g.k.Ys=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=f1(a);if(f){var h=xEa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Gp(f||"");m&&n&&(n.v||n.list)?e.context.G.Fi(n.v,b,n.list,!1):g.cK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);C1(this.context.logger,c,l,d);wEa(f)||(c=g.ju(),d=b.itct,c&&d&&g.Au(c,g.du(d)))}};
g.k.da=function(){this.za.clear();this.Da.clear();g.I.prototype.da.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.K(this,a);return a.element};g.u(r1,m1);g.k=r1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Hg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Ys=function(){var a=this.isAvailable();g.Ig(this.element,a);g.N(this.context.G.getRootNode(),g.gT.IV_DRAWER_ENABLED,a);I0(this.G)};
g.k.destroy=function(){this.G.tp(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.Ho(this.X);g.bp(this.ca);this.ma&&this.ma.dispose();this.C&&this.C.dispose();m1.prototype.destroy.call(this)};
g.k.CK=function(){if(this.u){C1(this.context.logger,w1(this).kg.close);var a=g.ju();a&&this.J&&g.Au(a,this.J);q1(this)}};
g.k.NK=function(){g.N(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.ZL=function(){var a=g.ju(),b=w1(this);b=b?b.Sd:this.Sd;a&&b&&g.yu(a,[b])};
g.k.YL=function(){var a=g.ju(),b=w1(this);b=b?b.Sd:this.Sd;a&&b&&g.zu(a,[b])};
g.k.eJ=function(){var a=w1(this);C1(this.context.logger,a.kg.WG);var b=g.ju();b&&a&&g.yu(b,[a.Lh,a.Sd])};
g.k.bM=function(){var a=g.ju(),b=w1(this);a&&b&&g.zu(a,[b.Lh])};
g.k.dJ=function(a){var b=w1(this),c=g.ju();this.i?a?(a=this.context.logger,C1(a,b.kg.gv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Lh&&g.Au(c,b.Lh)):(a=this.context.logger,C1(a,b.kg.gv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Sd&&g.Au(c,b.Sd)):(a=this.context.logger,C1(a,b.kg.gv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Sd&&g.Au(c,this.Sd))};g.u(x1,m1);x1.prototype.Tr=function(){m1.prototype.Tr.call(this);LEa(this)};
x1.prototype.show=function(){m1.prototype.show.call(this);var a=g.ju(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.yu(a,[g.du(b.itct)])};
x1.prototype.hide=function(){m1.prototype.hide.call(this);var a=g.ju(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zu(a,[g.du(b.itct)])};g.u(y1,x1);
y1.prototype.show=function(){if(!this.isActive){x1.prototype.show.call(this);if(!this.J){g.M(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",ka:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ig(this.l,!1);var b=this.createElement({D:"div",ka:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=sEa(this.annotation))&&n1(this,this.l,b,this.annotation.id,
a.session_data);PEa(this,a);this.J=!0}g.Ig(this.element,!0);this.isActive=!0;this.l&&MEa(this,this.l)}};
y1.prototype.hide=function(){this.isActive&&(x1.prototype.hide.call(this),g.Ig(this.element,!1),this.isActive=!1)};
y1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);x1.prototype.destroy.call(this)};g.u(z1,x1);g.k=z1.prototype;g.k.show=function(){this.isActive||(x1.prototype.show.call(this),this.W||(REa(this),this.W=!0),g.Ig(this.element,!0),g.Lm(function(){g.rn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,B1(this),SEa(this),TEa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.lw=function(a,b,c,d,e,f){return this.isCollapsed?!1:x1.prototype.lw.call(this,a,b,c,d,e,f)};
g.k.uL=function(a){this.L=!0;A1(this,500,a)};
g.k.tL=function(){this.L=!1;UEa(this)};
g.k.nL=function(a){a.stopPropagation();this.hide()};
g.k.oL=function(a){a.stopPropagation();B1(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();x1.prototype.destroy.call(this)};g.u(D1,g.HN);g.k=D1.prototype;g.k.Ge=function(a,b){if(!hFa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.t_(b);c&&E1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.i&&(CEa(this.i,b),I0(this.player)),!0}return null};
g.k.getOptions=function(){return hFa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.En=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.pE||a.L.get(b.videoId)||g.CI(b)||g.DI(b)?!0:!1};
g.k.Du=function(){if(this.B){var a=this.player.Ja().getVideoContentRect(!0);g.Gg(this.B.element,a.width,a.height);g.zg(this.B.element,a.left,a.top)}if(this.i){var b=this.player.cj();a=this.i;b=b.width;g.N(a.B,"iv-drawer-small",426>=b);g.N(a.B,"iv-drawer-big",1280<=b)}};
g.k.fJ=function(a){XEa(this,a.state);g.V(a.state,2)&&(this.Lg()&&this.Ni()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.tp(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Sp(h)&&h.responseXML?h.responseXML:null)&&(E1(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.HN.prototype.load.call(this);XEa(this,this.player.Va());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rp()&&(a=$Ea(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&aFa(e,f);f=f&&(f.ht||f.mq);if(!c.Fk||f)c.ca?YEa(this,c.ca,e):(this.u=function(){b.Oa(e)},this.player.addEventListener("videodatachange",this.u));
g.xN(this.player,this.B.element,4);this.Du();(f=g.CI(c))&&fFa(this,f);(f=g.DI(c))&&f.featuredChannel&&gFa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Oa=function(a){var b=this.player.getVideoData();b.ca&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),YEa(this,b.ca,a))};
g.k.unload=function(){this.player.Oe("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,I0(this.player));this.W=!1;this.I&&(this.I.abort(),this.I=null);this.J={};this.l.hide();g.HN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.QF=function(a){a===this.player.getVideoData().videoId&&(this.loaded?bFa(this):this.load())};
g.k.Lg=function(){return!!this.i&&this.i.isAvailable()};
g.k.Ni=function(){this.Lg();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Lg();this.i&&(a?c?p1(this.i,c,b):p1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):q1(this.i))};
g.k.tp=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.da=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.QF,this);g.rn(this.player.getRootNode(),g.gT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.sp(a[b]);this.X.length=0;g.HN.prototype.da.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.K(this,a);return a.element};g.NN.annotations_module=D1;g.NN.creatorendscreen=U0;})(_yt_player);
